### ISSUE TITLE
Unlock all starters not unlocking forms

### ISSUE THREAD

**Issue by draculgras** [fire6945/RogueEditor#10]
We spoke about this briefly on reddit and you said i should post an issue, but specific pokemon only get their base form unlocked using the unlock all starters cheat, for example oricorio base fire form is unlocked but the other 3 are not, and rotom base is unlocked but none of their other forms are. this is consistent with all pokemon that have unlockable forms through the starter select screen

**Comment by fire6945** [comment]
I sent you a reply: I come bearing bad news. Currently, there is no way to unlock different Pokemon variants. It isn't an issue with RogueEditor, it's on Pokerogue's server side. Sorry about that.

**Comment by claudiunderthehood** [comment]
> We spoke about this briefly on reddit and you said i should post an issue, but specific pokemon only get their base form unlocked using the unlock all starters cheat, for example oricorio base fire form is unlocked but the other 3 are not, and rotom base is unlocked but none of their other forms are. this is consistent with all pokemon that have unlockable forms through the starter select screen

Sadly it appears to be impossible. After checking PokeRogue code line after line we've came to the conclusion that the form is generated when hatching or while battling randomly by the Server, there isn't even a field for the pokemons with multiple forms to handle those, so yeah, there isn't much we can do. Sorry.
