### ISSUE TITLE
[Suggestion] Add “upgrade all” option 

### ISSUE THREAD

**Issue by FuecocoBoi09** [fire6945/RogueEditor#3]
Make a option to make all Pokémon have all candy unlocks unlocked.

**Comment by fire6945** [comment]
Good idea

**Comment by fire6945** [comment]
Actually, I think they already do get unlocked when you use the command to unlock all starters.

**Comment by FuecocoBoi09** [comment]
You get the nessesary candys, just have to click a lot.

**Comment by longxa762** [comment]
Dump your trainer data then change all the value of passiveAttr to 3 and valueReduction to 2, update your data and enjoy. 

```
      "passiveAttr": 3,
      "valueReduction": 2,
```

I'm not sure if the value is the limit though, some pokemon don't have a passive either so for those you have to manual relock their passive otherwise game will crash.
