### ISSUE TITLE
[Suggestion] A document with all biomes and their respective number listed

### ISSUE THREAD

**Issue by nyanzan** [fire6945/RogueEditor#6]
When modifying your save slot JSON it is useful to know these things. For example, going to fairy cave is relatively rare, but when you change your ''biome'' under arena to 28, you get transported to fairy cave instantly. It effectively allows you to warp between biomes.

**Comment by claudiunderthehood** [comment]
#6 You're right, i'll make something to list the biomes with their respective IDs so you can list them and display them like the Pokemon list.

**Comment by claudiunderthehood** [comment]
#

> When modifying your save slot JSON it is useful to know these things. For example, going to fairy cave is relatively rare, but when you change your ''biome'' under arena to 28, you get transported to fairy cave instantly. It effectively allows you to warp between biomes.

I've implemented your request on the test branch :)

**Comment by claudiunderthehood** [comment]
#8
